### ISSUE TITLE
♻️ Job Category Enum Type 제거

### ISSUE THREAD

**Issue by TaeyeonRoyce** [YAPP-Github/21st-Web-Team-2-BE#24]
## 🔖 리팩토링 내용
직군을 입력 받을때, [기타(ETC)]로 사용자가 임의로 입력할 수 있어 미리 지정 해둔 값으로 할당하기 어려워짐.
JobCategory(enumerated type) -> String으로 변환

**Comment by jimin3263** [comment]
제가 건드리면서 하겠습니다!!

**Comment by TaeyeonRoyce** [comment]
#26 에서 카테고리로 조건 조회 하는데, 단순 String 타입으로 응답해도 괜찮을지 의논하면 좋을 것 같습니다..!
